executable = $(filename)
Proxy_path = /afs/cern.ch/user/s/ssaumya/private/x509up_u122184
arguments = $(Proxy_path) $Fp(filename) $(ClusterID) $(ProcId)
output = $Fp(filename)hlt.stdout
error = $Fp(filename)hlt.stderr
log = $Fp(filename)hlt.log
+JobFlavour = "tomorrow"
queue filename matching (/afs/cern.ch/work/s/ssaumya/private/Egamma/CMSHLT-3764/CMSSW_16_0_5/src/EGamma-Studies/CMSHLT-3746_2026/Jobs/Job_*/*.sh)